### PR TITLE
ojo_fee_translate()

### PR DESCRIPTION
**Pull request by andrewjbe**
New function that takes a df from the "oscn_mins_" / "oscn_pays_" tables and returns the df with two new columns:
- code_description is the "translation" of the code
- code_category is the category of that fee code (like "Jail Costs", "Indigent Defense", "Procedural Court Fees", etc.)

The CSV with the translations isn't 100% exhaustive yet so that's something I can continue to work on

### CODE REVIEW

**Comment by brancengregory** [comment]
I think it would be good to keep to the tidy conventions, particularly in the main package.
`df %>% left_join(t, by = "min_code")`

That might take care of the column order, so you don't manually have to change it. Not sure.

**Comment by brancengregory** [comment]
Other than that, I think it looks good, albeit Ryan is the only one with the info to make sure the categories look good, so that's up to him. Great idea, and great work over all!

**Comment by rcgentzler** [comment]
I love this idea. I'd like this to follow the structure used by the courts to categorize fees:

- `acct_code`: Code of the deposit account ("A01", "A31", etc.)
- `fee_code`: Code of the fee on OSCN ("AFIS", "CHAB", etc.)
- `fee_desc`: Description of the fee
- `agency`: name of the agency that receives the funds
- `branch`: is the agency judicial or executive?
- `casetypes`: civil, criminal, or both?

You should be able to get nearly all of this from these documents:

- https://www.okhouse.gov/Documents/InterimStudies/2014/14-033%20Accounting%20Codes%20Handout.pdf
- https://www.okhouse.gov/Documents/InterimStudies/2014/14-033%20Summary%20of%20Court%20Collections%202007-2014%20Handout.pdf

**Comment by brancengregory** [comment]
Document's linked above are now located here:

- https://former.okhouse.gov/Documents/InterimStudies/2014/14-033%20Accounting%20Codes%20Handout.pdf
- https://former.okhouse.gov/Documents/InterimStudies/2014/14-033%20Summary%20of%20Court%20Collections%202007-2014%20Handout.pdf

**Pull request closed without merging**
